### ISSUE TITLE
Question on presets and static values

### ISSUE THREAD

**Issue by scaldara55** [toinsson/pyrealsense#3]
There are two arrays for presets (ivcam_presets and depth_control_presets).

1. Where did you get the values for these presets?
2. What is "ivcam"?
3. Ivcam option ENUMs reference two sensors (SR300, F200).  Does it also apply to R200?
4. Near the end of real sense.c there are a number of values pertaining to translation, rotation, and intrinsics for color and depth.  Where did these values come from and will the values be different for the different sensors.

**Comment by toinsson** [comment]
so

1. the value for the presets are taken from [rsutils.h](https://github.com/IntelRealSense/librealsense/blob/master/include/librealsense/rsutil.h). I copy/pasted this in the code to be able to have my own presets under the number 9.

2. ivcam might stand for infrared. There is an iv stream you can access on SR300. 

3. I don't think so, as we saw in #1, it makes your R200 crash.

4. These values are camera specific. I store them hardcoded in the code so I can access them without having the camera plugged in. Otherwise, they are loaded on context creation via:
```    
    rs_get_stream_intrinsics(dev, RS_STREAM_DEPTH, &depth_intrin, &e);
    check_error();
    rs_get_device_extrinsics(dev, RS_STREAM_DEPTH, RS_STREAM_COLOR, &depth_to_color, &e);
    check_error();
    rs_get_stream_intrinsics(dev, RS_STREAM_COLOR, &color_intrin, &e);
    check_error();
```

you can see your values with a call to `get_rs_intrinsics` and `get_rs_intrinsics`.
