### ISSUE TITLE
librealsense and rsutilwrapper not found

### ISSUE THREAD

**Issue by weiguochow** [toinsson/pyrealsense#68]
| Required Info  |   |
|---|---|
| Camera Model | SR300 | 
| Firmware Version |3.21.0.0   | 
| Operating System & Version | Ubuntu16.04|
| librealsense version | 1.12.0 |
| pyrealsense version | 1.2|

Hi,

There are some errors when run the examples/show_cv2.py. The rgb channel is normal,  but depth channel are all red.
Can you give me some advice?
regards,
weiguo

**Comment by toinsson** [comment]
you might need to re-run the patching script from librealsense, e.g. `patch-uvcvideo-16.04.simple.sh` - this issue happens when you update your machine/kernel (through a restart for example). 

This issue is not `pyrealsense` related: you would get the same symptoms by checking with `librealsense` examples, I'll close it.
